# Generated by Django 3.2 on 2022-12-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_libro_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='presentacion',
            options={'verbose_name': 'Presentación', 'verbose_name_plural': 'Presentación'},
        ),
    ]
